### PR TITLE
some cleanup

### LINKED ISSUE #56: Remove V1 types
Now that we only support we should at some point remove the V1 types.

However they are still used in `swarm migrate`. 
So the question because how long we want to keep that, or do we want to move the V1 types to other repo and update `swarm migrate` accordingly?

### LINKED ISSUE #63: links.go should be renamed to link.go
To align code more to our naming schemas we should clean this up. See https://github.com/giantswarm/user-config/pull/60#discussion-diff-39395750

### PR DESCRIPTION
**Pull request by zyndiecate**
fixes #63 
fixes #56 

ping @ewoutp

### CODE REVIEW

**Comment by zyndiecate** [comment]
ping @ZeissS

**Comment by ZeissS** [comment]
LGTM

**Comment by ewoutp** [comment]
This has now broken app-def-transf-go, app-client-go & client-go and will make `swarm migrate` impossible. Let's clean that up also

**Comment by zyndiecate** [comment]
On purpose yes. We pin our libs. Feel free to assign issues to me. I will take care.

**Comment by ewoutp** [comment]
See

- giantswarm/app-service#469
- giantswarm/api#166
- giantswarm/client-go#74
- giantswarm/app-client-go#40
- giantswarm/app-def-transf-go#19

cli follows soon

**Pull request merged**
